@Assessment_back_end_HostAddress = https://assessment-luuk.azurewebsites.net

POST {{Assessment_back_end_HostAddress}}/Artikel/
Content-Type: application/json

{
  "Code": "ABC1234DEF",
  "Naam": "Chrysant",
  "PotMaat": 12,
  "PlantHoogte": 23,
  "ProductGroep": "planten"
}

###

PUT {{Assessment_back_end_HostAddress}}/Artikel/
Content-Type: application/json

{
  "Code": "ABC1234DEF",
  "Naam": "Chrysant",
  "PotMaat": 12,
  "PlantHoogte": 23,
  "Kleur": "Geel",
  "ProductGroep": "planten"
}

###

GET {{Assessment_back_end_HostAddress}}/Artikel/
Accept: application/json

###

DELETE {{Assessment_back_end_HostAddress}}/Artikel/ABC1234DEF

###
